import type {
  DashboardHomeEventStateKey,
  DashboardHomeModuleKey,
  DashboardHomeStateData,
  DashboardHomeSummonEvent,
  DashboardVoiceSequence,
} from "./dashboardHome.types";

export const dashboardHomeStateGroups: { key: DashboardHomeModuleKey; label: string; states: DashboardHomeEventStateKey[] }[] = [
  {
    key: "tasks",
    label: "任务",
    states: ["task_working", "task_highlight", "task_completing", "task_done", "task_error_permission", "task_error_blocked", "task_error_missing_info"],
  },
  {
    key: "notes",
    label: "便签",
    states: ["notes_processing", "notes_reminder", "notes_scheduled"],
  },
  {
    key: "memory",
    label: "镜子",
    states: ["memory_summary", "memory_habit"],
  },
  {
    key: "safety",
    label: "安全",
    states: ["safety_alert", "safety_guard"],
  },
];

export const dashboardHomeStates: Record<DashboardHomeEventStateKey, DashboardHomeStateData> = {
  task_working: {
    key: "task_working",
    module: "tasks",
    label: "推进中",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(159,183,216,0.34)",
    accentColor: "#7C9EC8",
    tag: "正在推进",
    tagTone: "active",
    headline: "正在整理当前任务的真实信号",
    subline: "这里只保留返回的任务摘要，不再放入来源计数类示意文案。",
    progress: 42,
    progressLabel: "执行中",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "资料检索", status: "done" },
      { label: "信息整理", status: "active" },
      { label: "生成结果", status: "pending" },
    ],
    context: [
      { iconKey: "search", text: "已接入当前任务概览", time: "刚刚", type: "normal" },
      { iconKey: "sparkles", text: "优先展示返回的重点信号", time: "刚刚", type: "normal" },
      { iconKey: "loader", text: "正在对齐任务主链路", time: "进行中", type: "active" },
    ],
    breathSpeed: 1.8,
  },
  task_highlight: {
    key: "task_highlight",
    module: "tasks",
    label: "新进展",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(159,183,216,0.4)",
    accentColor: "#F4B183",
    tag: "值得关注",
    tagTone: "highlight",
    headline: "发现 2 个值得优先处理的风险点",
    subline: "竞品定价策略出现明显调整，用户留存数据也在异常波动，我已经把它们拖到视线最前。",
    progress: 58,
    progressLabel: "发现重点",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "资料检索", status: "done" },
      { label: "风险筛查", status: "active" },
      { label: "生成结果", status: "pending" },
    ],
    context: [
      { iconKey: "alert", text: "竞品定价策略重大调整", time: "刚刚", type: "warn" },
      { iconKey: "alert", text: "用户留存出现异常波动", time: "刚刚", type: "warn" },
      { iconKey: "flag", text: "已标记为优先项", type: "hint" },
    ],
    breathSpeed: 2.1,
  },
  task_completing: {
    key: "task_completing",
    module: "tasks",
    label: "接近完成",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(159,183,216,0.28)",
    accentColor: "#A9C3B0",
    tag: "接近完成",
    tagTone: "done",
    headline: "草稿已就绪，下一步只需你确认",
    subline: "报告初稿已经生成，建议先快速看结论部分。确认发送对象后，我可以立即继续。",
    progress: 85,
    progressLabel: "待确认",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "资料检索", status: "done" },
      { label: "草稿生成", status: "done" },
      { label: "待你确认", status: "active" },
    ],
    context: [
      { iconKey: "file", text: "报告初稿已生成", time: "刚刚", type: "normal" },
      { iconKey: "eye", text: "建议先看结论部分", type: "hint" },
      { iconKey: "send", text: "确认后即可发出", type: "hint" },
    ],
    anomaly: {
      title: "草稿已就绪，等待你确认",
      desc: "确认发送对象后，我可以立即帮你发出这份结果。",
      actionLabel: "确认发送",
      dismissLabel: "再看看",
      severity: "info",
    },
    breathSpeed: 1.3,
  },
  task_done: {
    key: "task_done",
    module: "tasks",
    label: "已完成",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(159,183,216,0.2)",
    accentColor: "#A9C3B0",
    tag: "已完成",
    tagTone: "done",
    headline: "会议纪要已经整理完成",
    subline: "本次任务已经全部收束，共处理 3 个议题并生成 1 份摘要，现在只需决定后续怎么复用。",
    progress: 100,
    progressLabel: "全部完成",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "资料检索", status: "done" },
      { label: "草稿生成", status: "done" },
      { label: "已完成", status: "done" },
    ],
    context: [
      { iconKey: "check", text: "3 个议题全部处理完成", time: "刚刚", type: "normal" },
      { iconKey: "file", text: "摘要已生成，共 1 份", type: "normal" },
      { iconKey: "user", text: "待确认发送对象", type: "hint" },
    ],
    breathSpeed: 0.7,
  },
  task_error_permission: {
    key: "task_error_permission",
    module: "tasks",
    label: "缺少权限",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(251,113,133,0.42)",
    accentColor: "#E493A8",
    tag: "需要介入",
    tagTone: "error",
    headline: "缺少访问权限，当前步骤无法继续",
    subline: "无法读取「Q3 财务数据」文件夹。你确认授权后，我就可以立即继续推进。",
    progress: 55,
    progressLabel: "推进受阻",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "资料检索", status: "done" },
      { label: "权限缺失", status: "error" },
      { label: "待解决", status: "pending" },
    ],
    context: [
      { iconKey: "check", text: "检索阶段已完成", time: "2 分钟前", type: "normal" },
      { iconKey: "lock", text: "无法读取 Q3 财务数据", time: "刚刚", type: "error" },
      { iconKey: "question", text: "等待你授权后继续", type: "hint" },
    ],
    anomaly: {
      title: "缺少访问权限",
      desc: "Q3 财务数据文件夹不可访问，放行后我就继续。",
      actionLabel: "前往授权",
      dismissLabel: "稍后处理",
      severity: "error",
    },
    breathSpeed: 2.2,
  },
  task_error_blocked: {
    key: "task_error_blocked",
    module: "tasks",
    label: "步骤阻塞",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(251,113,133,0.4)",
    accentColor: "#F4B183",
    tag: "步骤阻塞",
    tagTone: "error",
    headline: "当前步骤被阻塞，暂时无法自动继续",
    subline: "依赖的上游任务尚未完成，你需要决定是跳过还是继续等待。",
    progress: 38,
    progressLabel: "阻塞中",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "上游阻塞", status: "error" },
      { label: "等待处理", status: "pending" },
      { label: "继续推进", status: "pending" },
    ],
    context: [
      { iconKey: "link", text: "依赖「数据清洗」任务", time: "未完成", type: "error" },
      { iconKey: "pause", text: "当前步骤已暂停", time: "5 分钟前", type: "warn" },
      { iconKey: "question", text: "跳过还是等待，需要你决定", type: "hint" },
    ],
    anomaly: {
      title: "上游任务阻塞",
      desc: "「数据清洗」尚未完成，是否跳过并继续推进？",
      actionLabel: "跳过继续",
      dismissLabel: "继续等待",
      severity: "error",
    },
    breathSpeed: 2.4,
  },
  task_error_missing_info: {
    key: "task_error_missing_info",
    module: "tasks",
    label: "缺少信息",
    orbColor: "#9FB7D8",
    orbGlow: "rgba(244,177,131,0.38)",
    accentColor: "#F4B183",
    tag: "还差一项",
    tagTone: "warn",
    headline: "还差一项关键信息，当前无法继续",
    subline: "需要补充目标受众的地区范围，才能完成受众分析这一步。",
    progress: 48,
    progressLabel: "信息不足",
    progressSteps: [
      { label: "任务启动", status: "done" },
      { label: "初步分析", status: "done" },
      { label: "信息缺失", status: "error" },
      { label: "深度分析", status: "pending" },
    ],
    context: [
      { iconKey: "check", text: "初步分析已完成", time: "1 分钟前", type: "normal" },
      { iconKey: "info", text: "缺少：目标受众地区范围", time: "刚刚", type: "warn" },
      { iconKey: "edit", text: "补充后可以立即继续", type: "hint" },
    ],
    anomaly: {
      title: "还差一项关键信息",
      desc: "请提供目标受众的地区范围，例如华东 / 全国 / 海外。",
      actionLabel: "补充信息",
      dismissLabel: "跳过此步",
      severity: "warn",
    },
    breathSpeed: 2,
  },
  notes_processing: {
    key: "notes_processing",
    module: "notes",
    label: "便签处理中",
    orbColor: "#F4B183",
    orbGlow: "rgba(244,177,131,0.34)",
    accentColor: "#F6C5A1",
    tag: "异步处理",
    tagTone: "active",
    headline: "正在处理你昨晚留下的 3 条便签",
    subline: "已经识别出 2 项可直接执行的任务，还有 1 项需要你确认优先级。",
    context: [
      { iconKey: "note", text: "整理 Q3 复盘要点 — 已开始", time: "进行中", type: "active" },
      { iconKey: "note", text: "联系设计师确认排期 — 已识别", time: "待执行", type: "normal" },
      { iconKey: "question", text: "下周汇报材料 — 需确认优先级", type: "hint" },
    ],
    notes: [
      { id: "note_1", text: "整理 Q3 复盘要点", status: "processing", time: "进行中", tag: "文档" },
      { id: "note_2", text: "联系设计师确认排期", status: "pending", time: "待执行", tag: "沟通" },
      { id: "note_3", text: "下周汇报材料准备", status: "pending", time: "需确认", tag: "优先级?" },
    ],
    breathSpeed: 1.5,
  },
  notes_reminder: {
    key: "notes_reminder",
    module: "notes",
    label: "重复提醒",
    orbColor: "#F4B183",
    orbGlow: "rgba(244,177,131,0.38)",
    accentColor: "#D49F73",
    tag: "我记住了",
    tagTone: "highlight",
    headline: "你每周一都会整理周报，现在正好是这个时段",
    subline: "上周的数据摘要已经准备好，你可以直接开始写，也可以让我先起一版草稿。",
    context: [
      { iconKey: "repeat", text: "已连续识别 6 周的周报习惯", type: "hint" },
      { iconKey: "chart", text: "上周数据摘要已就绪", time: "刚刚", type: "normal" },
      { iconKey: "edit", text: "可以直接起草或让我先写", type: "hint" },
    ],
    notes: [
      { id: "note_4", text: "周报整理（每周一）", status: "recurring", time: "今天", tag: "重复任务" },
      { id: "note_5", text: "上周数据摘要", status: "done", time: "已就绪", tag: "已准备" },
    ],
    breathSpeed: 1.1,
  },
  notes_scheduled: {
    key: "notes_scheduled",
    module: "notes",
    label: "定时任务",
    orbColor: "#F4B183",
    orbGlow: "rgba(159,183,216,0.22)",
    accentColor: "#9FB7D8",
    tag: "定时巡检",
    tagTone: "active",
    headline: "每日 9:00 巡检已经完成，发现 1 项需要关注",
    subline: "今日邮件中有 1 封来自重要客户的回复，已标记为优先处理，其余内容已经自动归档。",
    context: [
      { iconKey: "mail", text: "重要客户邮件回复 — 待处理", time: "刚刚", type: "warn" },
      { iconKey: "archive", text: "12 封邮件已自动归档", time: "9:00", type: "normal" },
      { iconKey: "calendar", text: "下次巡检：明日 9:00", type: "hint" },
    ],
    notes: [
      { id: "note_6", text: "重要客户邮件回复", status: "pending", time: "待处理", tag: "优先" },
      { id: "note_7", text: "日常邮件归档", status: "done", time: "已完成", tag: "自动" },
      { id: "note_8", text: "明日 9:00 巡检", status: "pending", time: "已排期", tag: "定时" },
    ],
    breathSpeed: 1,
  },
  memory_summary: {
    key: "memory_summary",
    module: "memory",
    label: "周期总结",
    orbColor: "#B9AEDC",
    orbGlow: "rgba(185,174,220,0.3)",
    accentColor: "#D7CDED",
    tag: "镜子",
    tagTone: "mirror",
    headline: "我帮你总结了最近两周反复出现的关注点",
    subline: "这不是报告，只是想让你知道，我已经把这些工作节奏和偏好记住了。",
    context: [],
    insights: [
      { iconKey: "focus", text: "你最常处理的是产品策略和竞品分析类任务", emphasis: true },
      { iconKey: "time", text: "你的高效时段集中在上午 10:00 - 12:00" },
      { iconKey: "repeat", text: "周报整理已成为稳定的每周一习惯" },
      { iconKey: "chat", text: "你倾向于先看结论，再决定是否深入" },
    ],
    breathSpeed: 0.8,
  },
  memory_habit: {
    key: "memory_habit",
    module: "memory",
    label: "习惯洞察",
    orbColor: "#B9AEDC",
    orbGlow: "rgba(185,174,220,0.34)",
    accentColor: "#E6DCF7",
    tag: "我注意到",
    tagTone: "mirror",
    headline: "你似乎形成了一种新的工作节奏",
    subline: "最近 3 周，你会在周四下午集中处理需要深度思考的任务，所以我给这个时段保留了更安静的提醒。",
    context: [],
    insights: [
      { iconKey: "brain", text: "周四下午是你的深度工作时段", emphasis: true },
      { iconKey: "mute", text: "我会把这个时段调整为低打扰模式" },
      { iconKey: "bulb", text: "适合把复杂任务安排在周四下午" },
    ],
    breathSpeed: 0.76,
  },
  safety_alert: {
    key: "safety_alert",
    module: "safety",
    label: "边界预警",
    orbColor: "#A9C3B0",
    orbGlow: "rgba(169,195,176,0.34)",
    accentColor: "#8FAA95",
    tag: "需要确认",
    tagTone: "safety",
    headline: "我感知到一个边界风险，需要你先看一眼",
    subline: "当前操作可能越过工作区边界并覆盖已有文件，我已经把它拦在真正执行之前。",
    context: [
      { iconKey: "shield", text: "可能影响工作区外对象", time: "现在", type: "error" },
      { iconKey: "refresh", text: "存在覆盖或删除风险", time: "现在", type: "warn" },
      { iconKey: "history", text: "已生成恢复点，可回退", type: "hint" },
    ],
    signals: [
      { iconKey: "shield", label: "风险等级", value: "中", level: "warn", translation: "建议先确认再继续" },
      { iconKey: "lock", label: "待授权", value: "1", level: "critical", translation: "存在一个待确认操作" },
      { iconKey: "history", label: "恢复点", value: "可用", level: "normal", translation: "当前已有回退点" },
    ],
    anomaly: {
      title: "检测到边界风险",
      desc: "本次操作可能覆盖已有文件，我已经先帮你拦住了。",
      actionLabel: "查看安全详情",
      dismissLabel: "稍后再看",
      severity: "warn",
    },
    breathSpeed: 1.9,
  },
  safety_guard: {
    key: "safety_guard",
    module: "safety",
    label: "边界稳定",
    orbColor: "#A9C3B0",
    orbGlow: "rgba(169,195,176,0.26)",
    accentColor: "#C0D4C7",
    tag: "当前安全",
    tagTone: "safety",
    headline: "当前边界状态稳定，可以安心继续推进",
    subline: "最近一轮操作都保持在工作区内，恢复点、授权和边界检查都处于正常状态。",
    context: [
      { iconKey: "check", text: "最近操作均保持在工作区内", type: "normal" },
      { iconKey: "history", text: "恢复点已更新，可随时回退", type: "normal" },
      { iconKey: "sparkles", text: "当前没有新的待授权项", type: "hint" },
    ],
    signals: [
      { iconKey: "shield", label: "风险等级", value: "低", level: "normal", translation: "边界稳定" },
      { iconKey: "lock", label: "待授权", value: "0", level: "normal", translation: "当前没有挂起请求" },
      { iconKey: "history", label: "恢复点", value: "最新", level: "normal", translation: "最近一次操作可追溯" },
    ],
    breathSpeed: 0.9,
  },
};

export const dashboardSummonTemplates: Omit<DashboardHomeSummonEvent, "id">[] = [
  {
    duration: 6400,
    message: "你有一个任务正在快速接近收尾",
    module: "tasks",
    nextStep: "点开任务页继续推进",
    priority: "urgent",
    reason: "当前主任务已经进入草稿确认阶段",
    stateKey: "task_completing",
  },
  {
    duration: 5600,
    message: "昨晚留下的便签里，有 2 条已经变成可执行事项",
    module: "notes",
    nextStep: "去便签页看我整理出来的顺序",
    priority: "normal",
    reason: "已识别 2 项可直接推进，1 项需确认优先级",
    stateKey: "notes_processing",
  },
  {
    duration: 5400,
    message: "镜子里浮出了一条新的节奏洞察",
    module: "memory",
    nextStep: "打开镜子页查看这周的模式总结",
    priority: "normal",
    reason: "我记住了你最近新的深度工作时段",
    stateKey: "memory_habit",
  },
  {
    duration: 5200,
    message: "有一条边界提醒值得你先看一眼",
    module: "safety",
    nextStep: "去安全页确认风险与恢复点摘要",
    priority: "low",
    reason: "当前有一项操作需要你确认是否继续",
    stateKey: "safety_alert",
  },
];

export const dashboardVoiceSequences: DashboardVoiceSequence[] = [
  {
    suggestion: "帮我看今天最重要的任务",
    echoPool: ["今天", "重点", "任务", "推进", "收尾"],
    fragments: ["查看今天重点任务", "继续推进当前主任务"],
    summary: "我会先带你进入任务页，继续推进当前最重要的任务。",
    executingSteps: ["正在读取任务列表…", "定位当前主任务…", "准备切换到任务页…", "马上打开"],
    module: "tasks",
  },
  {
    suggestion: "帮我整理一下便签",
    echoPool: ["便签", "整理", "提醒", "优先级", "草稿"],
    fragments: ["整理便签内容", "确认优先级"],
    summary: "我会先把最近的便签和提醒整理出来，再带你进入便签页。",
    executingSteps: ["正在读取便签…", "整理提醒与草稿…", "定位便签子页…", "马上打开"],
    module: "notes",
  },
  {
    suggestion: "我想看看最近的镜子总结",
    echoPool: ["镜子", "总结", "习惯", "洞察", "节奏"],
    fragments: ["查看最近两周总结", "回看新的习惯洞察"],
    summary: "我会打开镜子页，把最近的总结和习惯洞察带到你面前。",
    executingSteps: ["正在唤起镜子…", "读取总结摘要…", "整理习惯洞察…", "马上打开"],
    module: "memory",
  },
  {
    suggestion: "看看现在有没有安全提醒",
    echoPool: ["安全", "边界", "授权", "恢复点", "风险"],
    fragments: ["查看当前安全提醒", "确认待授权与恢复点"],
    summary: "我会带你进入安全页，先看当前的边界提醒与风险摘要。",
    executingSteps: ["正在读取风险摘要…", "整理授权与恢复点…", "定位安全子页…", "马上打开"],
    module: "safety",
  },
];
